export * from './routes'

export const USER_ROLES = {
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_USER: 'ROLE_USER',
} as const

// SEO Meta Constants
export const PAGE_KEYS = {
  HOME: 'HOME',
  // ABOUT: 'ABOUT',
  EVENTS: 'EVENTS',
  SOUND_LIGHT: 'SOUND_LIGHT',
  RENTAL: 'RENTAL',
  NEWS: 'NEWS',
  CONTACT: 'CONTACT',
  POST_DETAIL: 'POST_DETAIL',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
} as const;

export const PRODUCT_CATEGORIES = {
  // SOUND_LIGHT categories
  SOUND_LIGHT_LIGHTING: 'SOUND_LIGHT_LIGHTING', // Ánh sáng sự kiện
  SOUND_LIGHT_AUDIO: 'SOUND_LIGHT_AUDIO', // Âm thanh sự kiện
  SOUND_LIGHT_STAGE: 'SOUND_LIGHT_STAGE', // Sân khấu sự kiện
  // RENTAL categories
  RENTAL_TABLE: 'RENTAL_TABLE', // Bàn sự kiện
  RENTAL_CHAIR: 'RENTAL_CHAIR', // Ghế sự kiện
  RENTAL_FAN: 'RENTAL_FAN', // Quạt sự kiện
  RENTAL_TENT: 'RENTAL_TENT', // Nhà bạt không gian
  RENTAL_UMBRELLA: 'RENTAL_UMBRELLA', // Dù lệch tâm
  RENTAL_BACKDROP: 'RENTAL_BACKDROP', // Thi công backdrop
  RENTAL_STAGE: 'RENTAL_STAGE', // Thi công sân khấu
  RENTAL_OTHER: 'RENTAL_OTHER', // Thiết bị khác
} as const;

export type ProductCategory = typeof PRODUCT_CATEGORIES[keyof typeof PRODUCT_CATEGORIES];

export const CATEGORIES_BY_TYPE: Record<string, ProductCategory[]> = {
  [PAGE_KEYS.SOUND_LIGHT]: [
    PRODUCT_CATEGORIES.SOUND_LIGHT_LIGHTING,
    PRODUCT_CATEGORIES.SOUND_LIGHT_AUDIO,
    PRODUCT_CATEGORIES.SOUND_LIGHT_STAGE,
  ],
  [PAGE_KEYS.RENTAL]: [
    PRODUCT_CATEGORIES.RENTAL_TABLE,
    PRODUCT_CATEGORIES.RENTAL_CHAIR,
    PRODUCT_CATEGORIES.RENTAL_FAN,
    PRODUCT_CATEGORIES.RENTAL_TENT,
    PRODUCT_CATEGORIES.RENTAL_UMBRELLA,
    PRODUCT_CATEGORIES.RENTAL_BACKDROP,
    PRODUCT_CATEGORIES.RENTAL_STAGE,
    PRODUCT_CATEGORIES.RENTAL_OTHER,
  ],
};

export const LIMIT_OPTIONS = [10, 20, 50, 100]

export const TOAST_GROUP = 'MODAL_TOAST_GROUP'