export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
}

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    GET_ALL: '/users',
    GET_BY_ID: '/users/:id',
    GET_BY_ROLE: '/users/role/:role',
    UPDATE_PROFILE: '/users/profile',
    CHANGE_PASSWORD: '/users/change-password',
    GET_PROFILE: '/users/profile',
  },
  SEO: {
    BASE: '/seo',
    GET_ALL: '/seo',
    GET_BY_PAGE: '/seo/:pageKey',
    UPDATE: '/seo/:pageKey',
  },
  CONFIGS: {
    BASE: '/configs',
    GET_ALL: '/configs',
    GET_BY_GROUP: '/configs/group/:group',
    UPDATE: '/configs/:key',
    BULK_UPDATE: '/configs/bulk-update',
  },
  PRODUCTS: {
    BASE: '/products',
    GET_ALL: '/products',
    GET_BY_ID: '/products/:id',
    GET_BY_SLUG: '/products/slug/:slug',
    CREATE: '/products',
    UPDATE: '/products/:id',
    DELETE: '/products/:id',
  },
  POSTS: {
    BASE: '/posts',
    GET_ALL: '/posts',
    GET_BY_ID: '/posts/:id',
    GET_BY_SLUG: '/posts/slug/:slug',
    CREATE: '/posts',
    UPDATE: '/posts/:id',
    DELETE: '/posts/:id',
  },
  HIGHLIGHT_VIDEOS: {
    BASE: '/highlight-videos',
    GET_ALL: '/highlight-videos',
    GET_BY_ID: '/highlight-videos/:id',
    CREATE: '/highlight-videos',
    UPDATE: '/highlight-videos/:id',
    DELETE: '/highlight-videos/:id',
  },
  HOME_VIDEOS: {
    BASE: '/home-videos',
    GET_ALL: '/home-videos',
    GET_BY_ID: '/home-videos/:id',
    CREATE: '/home-videos',
    UPDATE: '/home-videos/:id',
    DELETE: '/home-videos/:id',
  },
  NEWSLETTER: {
    BASE: '/newsletter',
    SUBSCRIBE: '/newsletter/subscribe',
    GET_ALL: '/newsletter',
    UPDATE: '/newsletter/:id',
    DELETE: '/newsletter/:id',
  },
}
