export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
}

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH_TOKEN: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    GET_ALL: '/users',
    GET_BY_ID: '/users/:id',
    GET_BY_ROLE: '/users/role/:role',
    UPDATE_PROFILE: '/users/profile',
    CHANGE_PASSWORD: '/users/change-password',
    GET_PROFILE: '/users/profile',
  },
  SEO: {
    BASE: '/seo',
    GET_ALL: '/seo',
    GET_BY_PAGE: '/seo/:pageKey',
    UPDATE: '/seo/:pageKey',
  },
  CONFIGS: {
    BASE: '/configs',
    GET_ALL: '/configs',
    GET_BY_GROUP: '/configs/group/:group',
    UPDATE: '/configs/:key',
    BULK_UPDATE: '/configs/bulk-update',
  },
  PRODUCTS: {
    BASE: '/products',
    GET_ALL: '/products',
    GET_BY_ID: '/products/:id',
    GET_BY_SLUG: '/products/slug/:slug',
    CREATE: '/products',
    UPDATE: '/products/:id',
    DELETE: '/products/:id',
  },
  POSTS: {
    BASE: '/posts',
    GET_ALL: '/posts',
    GET_BY_ID: '/posts/:id',
    GET_BY_SLUG: '/posts/slug/:slug',
    CREATE: '/posts',
    UPDATE: '/posts/:id',
    DELETE: '/posts/:id',
  },
  HIGHLIGHT_VIDEOS: {
    BASE: '/highlight-videos',
    GET_ALL: '/highlight-videos',
    GET_BY_ID: '/highlight-videos/:id',
    CREATE: '/highlight-videos',
    UPDATE: '/highlight-videos/:id',
    DELETE: '/highlight-videos/:id',
  },
  HOME_VIDEOS: {
    BASE: '/home-videos',
    GET_ALL: '/home-videos',
    GET_BY_ID: '/home-videos/:id',
    CREATE: '/home-videos',
    UPDATE: '/home-videos/:id',
    DELETE: '/home-videos/:id',
  },
  NEWSLETTER: {
    BASE: '/newsletter',
    SUBSCRIBE: '/newsletter/subscribe',
    GET_ALL: '/newsletter',
    UPDATE: '/newsletter/:id',
    DELETE: '/newsletter/:id',
  },
  DASHBOARD: {
    OVERVIEW: '/dashboard/overview',
    YEARLY_CHARTS: '/dashboard/charts/yearly',
  },
  PARTNERS: {
    BASE: '/partners',
    GET_ALL: '/partners',
    GET_ACTIVE: '/partners/active',
    GET_BY_ID: '/partners/:id',
    CREATE: '/partners',
    UPDATE: '/partners/:id',
    DELETE: '/partners/:id',
  },
  CONTACT_MESSAGES: {
    BASE: '/contact-messages',
    GET_ALL: '/contact-messages',
    GET_BY_ID: '/contact-messages/:id',
    CREATE: '/contact-messages',
    MARK_AS_READ: '/contact-messages/:id/read',
    DELETE: '/contact-messages/:id',
  },
}

const ADMIN_BASE = '/wpadmin'

export const ADMIN_PATHS = {
  DASHBOARD: '',
  PRODUCTS: 'products',
  POSTS: 'posts',
  VIDEOS: 'videos',
  HOME_VIDEOS: 'home-videos',
  NEWSLETTER: 'newsletter',
  CONFIGS: 'configs',
  SEO: 'seo',
  PARTNERS: 'partners',
  CONTACT_MESSAGES: 'contact-messages',
  POSTS_CREATE: 'posts/create',
  POSTS_EDIT: 'posts/edit/:id',
  PRODUCTS_CREATE: 'products/create',
  PRODUCTS_EDIT: 'products/edit/:id',
}

export const ADMIN_ROUTES = {
  BASE: ADMIN_BASE,
  DASHBOARD: ADMIN_BASE,
  PRODUCTS: `${ADMIN_BASE}/${ADMIN_PATHS.PRODUCTS}`,
  POSTS: `${ADMIN_BASE}/${ADMIN_PATHS.POSTS}`,
  VIDEOS: `${ADMIN_BASE}/${ADMIN_PATHS.VIDEOS}`,
  HOME_VIDEOS: `${ADMIN_BASE}/${ADMIN_PATHS.HOME_VIDEOS}`,
  NEWSLETTER: `${ADMIN_BASE}/${ADMIN_PATHS.NEWSLETTER}`,
  CONFIGS: `${ADMIN_BASE}/${ADMIN_PATHS.CONFIGS}`,
  SEO: `${ADMIN_BASE}/${ADMIN_PATHS.SEO}`,
  PARTNERS: `${ADMIN_BASE}/${ADMIN_PATHS.PARTNERS}`,
  CONTACT_MESSAGES: `${ADMIN_BASE}/${ADMIN_PATHS.CONTACT_MESSAGES}`,
  POSTS_CREATE: `${ADMIN_BASE}/${ADMIN_PATHS.POSTS_CREATE}`,
  POSTS_EDIT: `${ADMIN_BASE}/${ADMIN_PATHS.POSTS_EDIT}`,
}

